# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.cache/wt [current_project]
set_property parent.project_path C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Randy/Desktop/Comp541/Lab10/Lab10.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/reg_data.mem
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/instr_data.mem
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/mem_data.mem
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/bitmap_data.mem
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/screen_data.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/sources_1/imports/new/fulladder.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/new/adder.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/shifter.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/logical.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/comparator.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/new/addsub.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/xycounter.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/register_file.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/ALU.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/ram_module.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/display640x480.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/vgatimer.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/bitmapmem.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/hexto7seg.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/fulldatapath.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/controller.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/screenmem.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/dmem.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/clockdivider_Nexys4.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/vgadisplaydriver.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/montek_sound_Nexys4.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/mips.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/keyboard.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/imem.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/display8digit.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/accelerometer.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/new/memIO.sv
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/top.sv
}
read_vhdl -library xil_defaultlib {
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/SPI_If.vhd
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/ADXL362Ctrl.vhd
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/AccelArithmetics.vhd
  C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/sources_1/imports/new/AccelerometerCtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/constrs_1/new/interface.xdc
set_property used_in_implementation false [get_files C:/Users/Randy/Desktop/Comp541/Lab10/Lab10.srcs/constrs_1/new/interface.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
